<?php
$title = 'Registro usuario administrador';
$this->headTitle($title);

$Cod_Empleado=$form->get('Cod_Empleado');
$Cod_Empleado->setAttribute('class', 'form-control autofocus');
$Cod_Empleado->setAttribute('readonly', 'readonly');

$Usuario=$form->get('Usuario');
$Usuario->setAttribute('class', 'form-control autofocus');
$Usuario->setAttribute('readonly', 'readonly');

$Correo=$form->get('Correo');
$Correo->setAttribute('class', 'form-control autofocus');
$Correo->setAttribute('readonly', 'readonly');


$ClaveView=$form->get('ClaveView');
$ClaveView->setAttribute('class', 'form-control autofocus');
$ClaveView->setAttribute('readonly', 'readonly');

$Rol=$form->get('Rol');
$Rol->setAttribute('class', 'form-control autofocus');

$Estado=$form->get('Estado');
$Estado->setAttribute('class', 'form-control autofocus');


$submit=$form->get('submit');
$submit->setAttribute('class', 'btn btn-primary btn-lg btn-block');

$form->prepare();

echo $this->form()->openTag($form);
?>                                                    
<form>
<div class="container">
<fieldset>
    <h3 class="text-center"><i class="fa fa-user-circle-o" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h3>
</fieldset> 
<div class="row">
    <div class="col-md-12 col-md-offset-3">
        <div class="row">
            <div class="col-md-12 col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($Cod_Empleado) ?>
                        <?= $this->formElement($Cod_Empleado) ?>
                        
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($Usuario) ?>
                        <?= $this->formElement($Usuario) ?>
                       
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($Correo) ?>
                        <?= $this->formElement($Correo) ?>
                       
                    </div>


                    <div class="form-group">
                        <?= $this->formLabel($ClaveView) ?>
                        <?= $this->formElement($ClaveView) ?>
                       

                     <div class="form-group">
                        <?= $this->formLabel($Rol) ?>
                        <?= $this->formElement($Rol) ?>
                       
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($Estado) ?>
                        <?= $this->formElement($Estado) ?>
                    </div>

                    
                    <?php
                    echo $this->formSubmit($submit);
                    echo $this->formHidden($form->get('Cod_Usuario'));
                    echo $this->form()->closeTag();
                    ?>
                   
             </div>       
        </div>
    </div>
</div>
</div>
</form>
