<?php
$title = 'Actualizar contraseña';
$this->headTitle($title);

$Clave=$form->get('Clave');
$Clave->setAttribute('class', 'form-control autofocus');

$Confirmarclave=$form->get('Confirmarclave');
$Confirmarclave->setAttribute('class', 'form-control autofocus');


$submit=$form->get('submit');
$submit->setAttribute('class', 'btn btn-primary btn-lg btn-block');

//$form->setAttribute('action', $this->url('departamento/add'));
$form->prepare();

echo $this->form()->openTag($form);
?>                                                    
<form>
<div class="container">
<fieldset>
    <h3 class="text-center"><i class="fa fa-lock" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h3>
</fieldset> 
<div class="row">
    <div class="col-md-12 col-md-offset-3">
        <div class="row">
            <div class="col-md-12 col-md-6">

                    <div class="form-group">
                        <?= $this->formLabel($Clave) ?>
                        <?= $this->formElement($Clave) ?>
                        <?= $this->formElementErrors()->render($Clave, ['class' => 'help-inline  text-danger']) ?>
                    </div>

                     <div class="form-group">
                        <?= $this->formLabel($Confirmarclave) ?>
                        <?= $this->formElement($Confirmarclave) ?>
                        <?= $this->formElementErrors()->render($Confirmarclave, ['class' => 'help-inline  text-danger']) ?>
                    </div>

                    <?php
                    echo $this->formSubmit($submit);
                    echo $this->formHidden($form->get('Cod_Usuario'));
                    echo $this->form()->closeTag();
                    ?>
                   
             </div>       
        </div>
    </div>
</div>
</div>
</form>
