<?php
$title = 'Eliminar unidad de transporte';
$url   = $this->url('unidadtransporte/delete',['Cod_Unidad'=>$unit->Cod_Unidad]);

$this->headTitle($title);
?>
<form action="<?= $url ?>" method="post">
<div class="container">
    <fieldset>
        <h3 class="text-center"><i class="fa fa-truck" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h3>
    </fieldset>
 <div class="row">
    <div class="col-md-12 col-md-offset-3">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                       <label>C&oacute;digo de  unidad de transporte</label>
                       <input class="form-control" type="text" name="Cod_Unidad" value= "<?= $this->escapeHtml($unit->Cod_Unidad) ?> "/>
                </div>
                <div class="form-group">
                        <label>Marca de veh&iacute;culo</label>
                        <input class="form-control" type="text" name="Marca_Vehiculo" value= "<?= $this->escapeHtml($unit->Marca_Vehiculo) ?>" />
                </div>
                 <div class="form-group">
                        <label>Modelo de  veh&iacute;culo</label>
                        <input class="form-control" type="text" name="Modelo_Vehiculo" value= "<?= $this->escapeHtml($unit->Modelo_Vehiculo) ?>" />
                </div>
                <div class="form-group">
                        <label>Placa de veh&iacute;culo</label>
                        <input class="form-control" type="text" name="Placa_Vehiculo" value= "<?= $this->escapeHtml($unit->Placa_Vehiculo) ?>" />
                </div>
                <div class="form-group">
                        <label>Estado</label>
                        <input class="form-control" type="text" name="Estado" value= "<?= $this->escapeHtml($unit->Estado) ?>" />
                </div>

                <div class="form-group">
                      <h4 class="text-danger text-center">¿Esta seguro que desea eliminar este registro?</h4>
                 </div>
                  <div class="form-group">
                      <h5 class="text-danger text-center">Esta acci&oacute;n no es revertible</h5>
                 </div>
                 <div class="form-group col text-center">
                <input type="hidden" name="Cod_Conductor" value="<?=$Cond->Cod_Conductor ?>" />
                <input type="submit" class="btn btn-danger  active " name="del" id="del"  value="Borrar" />
                <input type="submit" class="btn btn-success active " name="del" id="del" value="Cancelar" />
                </div>
           </div>
       </div>
     </div>
   </div>
</div>  
</form>      