<?php
$title = 'Listado de unidades de transporte';
$this->headTitle($title);
?>
<div class="container">
<h2><?= $this->escapeHtml($title) ?></h2>
<div>
   <p>
      <a class="btn btn-success menu" href="<?= $this->url('unidadtransporte/add')?>"><span class="glyphicon glyphicon-plus">Agregar</a></span></a>
   </p>
</div>
<table class="table table-striped table-bordered table-hover  dt-responsive nowrap" cellspacing="0"  id="example"  style="width:100%">
<thead style="background-color:brown;color:white;">
     <tr>
        <th>c&oacute;digo</th>
        <th>Marca de vehiculo</th>
        <th>Modelo de vehiculo</th>
        <th>Placa de vehiculo</th>
        <th>Estado</th>
        <th>Fecha de ingreso</th>
        <th>Fecha de actualizaci&oacute;n</th>
        <th>Acci&oacute;n</th>
    </tr>
</thead>
<tbody>
<?php foreach ($unit as $unit) : ?>
    <tr>
        <td><?= $this->escapeHtml($unit->Cod_Unidad) ?></td>
        <td><?= $this->escapeHtml($unit->Marca_Vehiculo) ?></td>
        <td><?= $this->escapeHtml($unit->Modelo_Vehiculo) ?></td>
        <td><?= $this->escapeHtml($unit->Placa_Vehiculo) ?></td>
        <td><?= $this->escapeHtml($unit->Estado) ?></td>
        <td><?= $this->escapeHtml($unit->Fecha_Ingreso) ?></td>
        <td><?= $this->escapeHtml($unit->Fecha_Actualizacion) ?></td>
        <td>
             <a  type="button" class="btn btn-primary btn-sm"  href="<?=$this->url('unidadtransporte/edit',['Cod_Unidad'=>$unit->Cod_Unidad])?>"><span class="glyphicon glyphicon-pencil"></span>Editar</a>
            <a type="button" class="btn btn-danger btn-sm" href="<?= $this->url('unidadtransporte/delete', ['Cod_Unidad'=>$unit->Cod_Unidad])?>"><span class="glyphicon glyphicon-remove"></span>  Eliminar</a>     
        </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatable/Spanish.json"
    }
    });
   });
</script>


  


  
  
  
        
        
