<?php
$title = 'Listado de boletas para guias de remisión';
$this->headTitle($title);
?>
<div class="container">
<h3><?= $this->escapeHtml($title) ?></h3>
<div>
   <p>
      <a class="btn btn-primary menu" href="<?= $this->url('boletasremision/add')?>"><span class="glyphicon glyphicon-plus">Agregar</a></span></a>
   </p>
</div>
<table class="table table-striped table-bordered table-hover  dt-responsive nowrap" cellspacing="0"  id="example"  style="width:100%">
<thead  style="background-color:brown;color:white;">
     <tr>
        <th>Sucursal</th>
        <th>c&oacute;digo de boleta</th>
        <th>Fecha de emisi&oacute;n</th>
        <th>Consecutivo</th>
        <th>Número de transferencia</th>
        <th>Acciones</th>
    </tr>
</thead>
<tbody>
<?php foreach ($Boletas as $a) : ?>
    <tr>
       <td><?= $this->escapeHtml($a->Nombre_Sucursal) ?></td>
        <td><?= $this->escapeHtml($a->Cod_Boleta) ?></td>
        <td><?= $this->escapeHtml($a->Fecha_Emision) ?></td>
        <td><?= $this->escapeHtml($a->Consecutivo_Actual_Establ."-".$a->Consecutivo_Actual_Punto."-".$a->Consecutivo_Actual_Tipo."-".$a->Consecutivo_Actual_Correlativo)?></td>
        <td><?= $this->escapeHtml($a->Num_Transferencia)?></td>
        <td>   
             <a type="button" class=" btn btn-primary btn-sm"  href="<?=$this->url('boletasremision/detalle',['Cod_Detalle'=>$a->Cod_Boleta])?>"><span class="glyphicon glyphicon-pencil"></span>Detalle</a>
            <a  type="button" class=" btn btn-danger btn-sm" href="<?= $this->url('boletasremision/reporte', ['Cod_Boleta'=>$a->Cod_Boleta])?>"><span class="glyphicon glyphicon-remove"></span>Reporte</a>       
        </td>     
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatable/Spanish.json"
    }
    });
   });
</script>