<?php
echo $this->doctype();
$title = 'Boleta de guía de remisión';
$this->headTitle($title);

$Fecha_Emision =$form->get('Fecha_Emision');
$Fecha_Emision->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Establ->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Punto->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Tipo->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Consecutivo_Actual_Correlativo->setAttribute('readonly', 'readonly');

$Motivo_Traslado=$form->get('Motivo_Traslado');
$Motivo_Traslado->setAttribute('readonly','readonly');

$Num_Transferencia=$form->get('Num_Transferencia');
$Num_Transferencia->setAttribute('readonly', 'readonly');

$Punto_Partida=$form->get('Punto_Partida');
$Punto_Partida->setAttribute('readonly', 'readonly');

$Punto_Destino=$form->get('Punto_Destino');
$Punto_Destino->setAttribute('readonly', 'readonly');

$Fecha_Inicio_Traslado=$form->get('Fecha_Inicio_Traslado');
$Fecha_Inicio_Traslado->setAttribute('readonly', 'readonly');

$Fecha_Final_Traslado=$form->get('Fecha_Final_Traslado');
$Fecha_Final_Traslado->setAttribute('readonly', 'readonly');

$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('disabled', 'disabled');

$Unidad_Transporte=$form->get('Unidad_Transporte');
$Unidad_Transporte->setAttribute('disabled', 'disabled');

$Conductor=$form->get('Conductor');
$Conductor->setAttribute('disabled', 'disabled');

$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');

$Usuario=$form->get('Usuario');
$Usuario->setAttribute('readonly', 'readonly');

$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');

$form->prepare();
echo $this->form()->openTag($form);
?>
<html lang="en">
     <head>
        <meta charset="utf-8">
        <?= $this->headTitle('La Armeria')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>      
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.css'))
        ?>
    </head>
    <body>
<div class="container"> 
    <div class="row">
      <div class="col-md-3">
          <div class="form-group">
            <img src="<?=$this->basePath('img/logo.png') ?>" style="text-align:right;" height="120%" class="img-thumbnail img-responsive"/>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <h3 style="text-align:center;"><i class="fa fa-id-card fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h3>
          </div>
        </div>
         <div class="col-md-3">
           <div class="form-group">
            <label style="text-align:left;">Membrete linea 1</label>
            <h5 style="text-align:left;">Membrete linea 2</h5>
            <p style="text-align:left;">Membrete linea 3</p>
            
          </div>
        </div>
    </div> 
    <div class="row">
        <h5>N&Uacute;MERO DE DOCUMENTO FISCAL</h5>
        <div class="col-md-1">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Establ) ?>
                <?= $this->formElement($Consecutivo_Actual_Establ) ?>
            </div>
        </div>

        <div class="col-md-1">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Punto) ?>
                <?= $this->formElement($Consecutivo_Actual_Punto) ?>
            </div>
        </div>

        <div class="col-md-1">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Tipo) ?>
                <?= $this->formElement($Consecutivo_Actual_Tipo) ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Correlativo) ?>
                <?= $this->formElement($Consecutivo_Actual_Correlativo) ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Usuario) ?>
                <?= $this->formElement($Usuario) ?>
            </div>
        </div>
    </div></br>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Fecha_Emision) ?>
                <?= $this->formElement($Fecha_Emision) ?>
             </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Autorizacion_Sar) ?>
                <?= $this->formElement($Autorizacion_Sar) ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Fecha_Inicio_Traslado) ?>
                <?= $this->formElement($Fecha_Inicio_Traslado) ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Fecha_Final_Traslado) ?>
                <?= $this->formElement($Fecha_Final_Traslado) ?>
            </div>
        </div>
  </div> 
  <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <?= $this->formLabel($Punto_Partida) ?>
                <?= $this->formElement($Punto_Partida) ?>
            </div>
        </div>
        
        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Motivo_Traslado) ?>
                <?= $this->formElement($Motivo_Traslado) ?>
            </div>
        </div>
  </div>

  <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <?= $this->formLabel($Punto_Destino) ?>
                <?= $this->formElement($Punto_Destino) ?>
             </div>
        </div>
        <div class="col-md-4">
             <div class="form-group">
                <?= $this->formLabel($Num_Transferencia) ?>
                <?= $this->formElement($Num_Transferencia) ?>
             </div>
        </div>
    
  </div>
  <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Sucursal) ?>
                <?= $this->formSelect($Sucursal) ?>
            </div>
        </div>
    
        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Unidad_Transporte) ?>
                <?= $this->formElement($Unidad_Transporte) ?>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Conductor) ?>
                <?= $this->formElement($Conductor) ?>
                <?= $this->form()->closeTag()?>
            </div>
      </div>
   </div>
    <div class="row">
       <div class="form-group">      
            <div class="col-md-12">
              <table class="table table-striped table-bordered" cellspacing="0"  style="width:100%">
                    <thead>
                      <tr>
                        <th>Código de Producto</th>
                        <th>Producto</th>
                        <th>Cantidad</th>
                      </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($detalle as $a) : ?>
                        <tr>
                        <td><?= $this->escapeHtml($a->Producto) ?></td>
                        <td><?= $this->escapeHtml($a->Nombre_Producto) ?></td>
                        <td><?= $this->escapeHtml($a->Cantidad) ?></td>
                        <?php endforeach; ?>
                        </tr>
                    </tbody>
              </table>
            </div>
        </div>
    </div>
  </div>
<?= $this->inlineScript()
            ->appendFile($this->basePath('js/jquery.min.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js')) 
?>
 