<?php
$title = 'Eliminar Departamento';
$url   = $this->url('departamento/delete',['Cod_Departamento'=>$dep->Cod_Departamento]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<form action="<?= $url ?>" method="post">
      <div class="row">
            <div class="col-xs-12 col-md-6">
                <div class="form-group">
                       <label>C&oacute;digo de departamento</label>
                       <input class="form-control" type="text" name="Id" value= "<?= $this->escapeHtml($dep->Cod_Departamento) ?> "/>
                </div>
                <div class="form-group">
                        <label>Nombre de departamento</label>
                        <input class="form-control" type="text" name="Id" value= "<?= $this->escapeHtml($dep->Nombre_Depto) ?>" />
                </div>
                <div class="form-group">
                        <label>C&oacute;digo de sucursal</label>
                        <input class="form-control" type="text" name="Id" value= "<?= $this->escapeHtml($dep->Sucursal) ?>" />
                </div>

                <div class="form-group">
                      <h4 class="text-danger text-center">¿Esta seguro que desea eliminar este registro?</h4>
                 </div>
                  <div class="form-group">
                      <h5 class="text-danger text-center">Esta acci&oacute;n no es revertible</h5>
                 </div>
                 <div class="form-group col text-center">
                <input type="hidden" name="Cod_Departamento" value="<?=$dep->Cod_Departamento ?>" />
                <input type="submit" class="btn btn-danger  active " name="del" id="del"  value="Yes" />
                <input type="submit" class="btn btn-success active " name="del" id="del" value="No" />
                </div>
           </div>
     </div>
              
</form>