<?php
$title = 'Eliminar registro de  conductor de unidad de transporte';
$url   = $this->url('conductor/delete',['Cod_Conductor'=>$Cond->Cod_Conductor]);

$this->headTitle($title);
?>
<form action="<?= $url ?>" method="post">
<div class="container">
  <fieldset>
      <h3 class="text-center"><i class="fa fa-id-card fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h3>
  </fieldset>
     <div class="row">
      <div class="col-md-12 col-md-offset-3">
          <div class="row">
            <div class="col-md-6 col-md-6">
                <div class="form-group">
                       <label>C&oacute;digo de conductor</label>
                       <input class="form-control" type="text" name="Cod_Conductor" value= "<?= $this->escapeHtml($Cond->Cod_Conductor) ?> "/>
                </div>
                <div class="form-group">
                        <label>Nombres</label>
                        <input class="form-control" type="text" name="Nombres_Conductor" value= "<?= $this->escapeHtml($Cond->Nombres_Conductor) ?>" />
                </div>
                 <div class="form-group">
                        <label>Apellidos</label>
                        <input class="form-control" type="text" name="Apellidos" value= "<?= $this->escapeHtml($Cond->Apellidos_Conductor) ?>" />
                </div>
                <div class="form-group">
                        <label>RTN</label>
                        <input class="form-control" type="text" name="RTN" value= "<?= $this->escapeHtml($Cond->Rtn) ?>" />
                </div>

                <div class="form-group">
                      <h4 class="text-danger text-center">¿Esta seguro que desea eliminar este registro?</h4>
                 </div>
                  <div class="form-group">
                      <h5 class="text-danger text-center">Esta acci&oacute;n no es revertible</h5>
                 </div>
                 <div class="form-group col text-center">
                <input type="hidden" name="Cod_Conductor" value="<?=$Cond->Cod_Conductor ?>" />
                <input type="submit" class="btn btn-danger  active " name="del" id="del"  value="Borrar" />
                <input type="submit" class="btn btn-success active " name="del" id="del" value="Cancelar" />
                </div>
           </div>
        </div>
      </div>
    </div>
  </div>              
</form>
