<?php
$title = 'Eliminar Producto';
$url   = $this->url('productos/delete',['Cod_Producto'=>$pro->Cod_Producto]);

$this->headTitle($title);
?>
<div class="container">
<form action="<?= $url ?>" method="post">
      <div class="row">
            <div class="col-md-6 col-md-6">
              <h4 class="panel"><i class="fa fa-list-alt" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
                <div class="form-group">
                       <label>C&oacute;digo de producto</label>
                       <input class="form-control" type="text" name="Cod_Producto" value= "<?= $this->escapeHtml($pro->Cod_Producto) ?> "/>
                </div>
                <div class="form-group">
                        <label>Nombre de producto </label>
                        <input class="form-control" type="text" name="Nombre_Producto" value= "<?= $this->escapeHtml($pro->Nombre_Producto) ?>" />
                </div>
                <div class="form-group">
                        <label>Descripci&oacute;n</label>
                        <input class="form-control" type="text" name="Descripcion" value= "<?= $this->escapeHtml($pro->Descripcion) ?>" />
                </div>
                <div class="form-group">
                      <h4 class="text-danger text-center">¿Esta seguro que desea eliminar este registro?</h4>
                 </div>
                  <div class="form-group">
                      <h5 class="text-danger text-center">Esta acci&oacute;n no es revertible</h5>
                 </div>
                 <div class="form-group col text-center">
                <input type="hidden" name="Cod_Producto" value="<?= $pro->Cod_Producto ?>" />
                <input type="submit" class="btn btn-danger  active " name="del" id="del"  value="Borrar" />
                <input type="submit" class="btn btn-success active " name="del" id="del" value="Cancelar" />
                </div>
           </div>
     </div>
              
</form>
</div>