<?php
$title = 'Listado de productos';
$this->headTitle($title);
?>
<div class="container">
<h2><?= $this->escapeHtml($title) ?></h2>
<div>
   <p>
      <a class="btn btn-success menu" href="<?= $this->url('productos/add')?>"><span class="glyphicon glyphicon-plus">Agregar</a></span></a>
   </p>
</div>
<table class="table table-striped table-bordered table-hover  dt-responsive nowrap" cellspacing="0"  id="example"  style="width:100%">
<thead style="background-color:brown;color:white;">
     <tr>
        <th>c&oacute;digo de producto</th>
        <th>Nombre de producto</th>
        <th>Descripci&oacute;n</th>
        <th>Fecha de ingreso</th>
        <th>Fecha de actualizaci&oacute;n</th>
        <th>Acci&oacute;n</th>
    </tr>
</thead>
<tbody>
<?php foreach ($product as $pro) : ?>
    <tr>
        <td><?= $this->escapeHtml($pro->Cod_Producto) ?></td>
        <td><?= $this->escapeHtml($pro->Nombre_Producto) ?></td>
        <td><?= $this->escapeHtml($pro->Descripcion) ?></td>
        <td><?= $this->escapeHtml($pro->Fecha_Ingreso) ?></td>
        <td><?= $this->escapeHtml($pro->Fecha_Actualizacion) ?></td>
        <td>
             
             <a type="button" class=" btn btn-primary btn-sm"  href="<?=$this->url('productos/edit',['Cod_Producto'=>$pro->Cod_Producto])?>"><span class="glyphicon glyphicon-pencil"></span>Editar</a>
            <a  type="button" class=" btn btn-danger btn-sm" href="<?= $this->url('productos/delete', ['Cod_Producto'=>$pro->Cod_Producto])?>"><span class="glyphicon glyphicon-remove"></span>Eliminar</a>       
        </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatable/Spanish.json"
    }
    });
   });
</script>


  


  
  
  
        
        
